#!/bin/bash
docdir="doc/luadoc"
rm -rf "$docdir"
mkdir "$docdir"
luadoc -d "$docdir" *.lua
find . -type f -name "*.html" |
while read f; do
	echo "Minifying $f..."
	html-minifier --collapse-whitespace --use-short-doctype --remove-comments --remove-redundant-attributes -o "$f" "$f"
done