#!/bin/sh
output=`cloc . --csv --exclude-dir nozip,lib --include-lang Lua`
filecount=`echo $output|awk {'print $1'}`
sloc=`echo $output|grep -oP "\\d* *\$"`
echo You\'ve written $sloc significant lines of Lua code across $filecount files\!